#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Glass.Resource", IsApplication=true)]

namespace Glass
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GlassExtensions.Resource.Attribute.blurRadius = global::Glass.Resource.Attribute.blurRadius;
			global::GlassExtensions.Resource.Attribute.downsampleFactor = global::Glass.Resource.Attribute.downsampleFactor;
			global::GlassExtensions.Resource.Attribute.overlayColor = global::Glass.Resource.Attribute.overlayColor;
			global::GlassExtensions.Resource.Color.default_overlay_color = global::Glass.Resource.Color.default_overlay_color;
			global::GlassExtensions.Resource.Integer.default_blur_radius = global::Glass.Resource.Integer.default_blur_radius;
			global::GlassExtensions.Resource.Integer.default_downsample_factor = global::Glass.Resource.Integer.default_downsample_factor;
			global::GlassExtensions.Resource.String.library_name = global::Glass.Resource.String.library_name;
			global::GlassExtensions.Resource.Styleable.PxBlurringView = global::Glass.Resource.Styleable.PxBlurringView;
			global::GlassExtensions.Resource.Styleable.PxBlurringView_blurRadius = global::Glass.Resource.Styleable.PxBlurringView_blurRadius;
			global::GlassExtensions.Resource.Styleable.PxBlurringView_downsampleFactor = global::Glass.Resource.Styleable.PxBlurringView_downsampleFactor;
			global::GlassExtensions.Resource.Styleable.PxBlurringView_overlayColor = global::Glass.Resource.Styleable.PxBlurringView_overlayColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int blurRadius = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int downsampleFactor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int overlayColor = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int default_overlay_color = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int p0 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int p1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int p2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int p3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int p4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int p5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int p6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int p7 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int p8 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int p9 = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int blurred_view = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int blurring_view = 2131230730;
			
			// aapt resource value: 0x7f080001
			public const int image0 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int image1 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int image2 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int image3 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int image4 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int image5 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int image6 = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int image7 = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int image8 = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int shuffle_button = 2131230731;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int default_blur_radius = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int default_downsample_factor = 2131034113;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070003
			public const int action_settings = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int app_name = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int hello = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int library_name = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PxBlurringView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int PxBlurringView_blurRadius = 0;
			
			// aapt resource value: 1
			public const int PxBlurringView_downsampleFactor = 1;
			
			// aapt resource value: 2
			public const int PxBlurringView_overlayColor = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
