#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GlassExtensions.Resource", IsApplication=false)]

namespace GlassExtensions
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int blurRadius = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int downsampleFactor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int overlayColor = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public static int default_overlay_color = 2130903040;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f020000
			public static int default_blur_radius = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int default_downsample_factor = 2130837505;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public static int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PxBlurringView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public static int PxBlurringView_blurRadius = 0;
			
			// aapt resource value: 1
			public static int PxBlurringView_downsampleFactor = 1;
			
			// aapt resource value: 2
			public static int PxBlurringView_overlayColor = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
